### ISSUE TITLE
Kluge Enhancements

### ISSUE THREAD

**Issue by habiblawal1** [joe-chacko/project-explorer#6]

**Comment by habiblawal1** [comment]
Possible an option to clear kluge list with one command. Maybe px f unkluge -all ?

Possibly a notication once you've imported everything for kluge as it can be easy to miss. E.g. a bigger notification that you've finally imported ras.instrument so you know to go clean your eclipse projects

When I added the project "px f k io.openliberty.org.apache.bcel" to kluge it didn't show up as a dependency

**Comment by joe-chacko** [comment]
The notification for installing all the dependencies for a kluge is obviated by PR #9.

The problem with `io.openliberty.org.apache.bcel` is a problem with the project setup in open liberty.
